next26

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,27 +1,4 @@
-name: cpp-linter
-
-on: pull_request
-
-jobs:
-  cpp-linter:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: cpp-linter/cpp-linter-action@v2
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          style: file
-#          repo-root: 
-
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: echo "Some files failed the linting checks!"
-        # for actual deployment
-        # run: exit 1
-
-    - name: Code Formatting
+name: Code Formatting
       os: linux
       dist: xenial
       language: minimal
@@ -53,6 +30,10 @@ jobs:
         - cd $HOME
       script:
         - docker run -v $HOME/build/R3BRootGroup/R3BRoot:/root/R3BRoot r3broot:${TRAVIS_COMMIT}
+        
+        run: echo "Some files failed the linting checks!"
+        # for actual deployment
+        # run: exit 1
 
 notifications:
   email:
@@ -60,3 +41,4 @@ notifications:
       - joseluis.rodriguez.sanchez@usc.es
     on_success: always
     on_failure: always
+
